crnlib: make CRNLIB_FORCE_INLINE functions extern because the compiler will override anyway
Avoids errors on macOS like:

duplicate symbol __ZN6crnlib5utils10write_le64EPvy in:
    crn_arealist.o
    crn_assert.o

Setting static instead of extern would also workaround the error but it's wrong
and would raise warnings on other systems like FreeBSD:

In file included from crunch/crnlib/crn_core.h:174:
crunch/crnlib/crn_utils.h:235:8: warning: 'gnu_inline' attribute without 'extern' in C++ treated as externally available, this changed in Clang 10 [-Wgnu-inline-cpp-without-extern]
static CRNLIB_FORCE_INLINE void write_be64(void* p, uint64 x) {
       ^
crunch/crnlib/crn_core.h:85:70: note: expanded from macro 'CRNLIB_FORCE_INLINE'
 #define CRNLIB_FORCE_INLINE inline __attribute__((__always_inline__, __gnu_inline__))
                                                                      ^

Setting extern fixes the duplicate symbols error on macOS without introducing
warnings on FreeBSD.